language: c

sudo: false

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - libfftw3-dev
    - cmake
    - libatlas-base-dev
  
env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
  matrix:
    - USE_FFTW_FFT=1
    - USE_OOURA_FFT=1
    - NO_CBLAS=1

script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ../FxDSP && make && make test-coverage

after_success:
  - cd ..
  - export PATH=$HOME/.local/bin:$PATH
  - pip install cpp-coveralls --user `whoami`
  - coveralls -r . -e doc -e FxDSP/test -e build/test -e build/CMakeFiles/CompilerIdC -e build/CMakeFiles/CompilerIdCXX --gcov-options '\-lp'


